language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
env:
  matrix:
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
   - DJANGO="Django<1.11"
install:
 - pip install "$DJANGO" coverage coveralls djangorestframework
 - pip install .
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django<1.10"
    - python: "3.3"
      env: DJANGO="Django<1.11"
branches:
 only:
  - master
script:
  - coverage run --source=drf_multiple_model manage.py test
after_success:
  - coverage report
  - coveralls
